include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
